// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VocalClerk.Infrastructure.Data;

#nullable disable

namespace VocalClerk.Infrastructure.Migrations
{
    [DbContext(typeof(VocalClerkDbContext))]
    [Migration("20260121063925_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("VocalClerk.Domain.Entities.AIProcessingResult", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(95)")
                        .HasColumnName("id");

                    b.Property<int>("ConfidenceScore")
                        .HasColumnType("int")
                        .HasColumnName("confidence_score");

                    b.Property<string>("ModelUsed")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("model_used");

                    b.Property<DateTime>("ProcessedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("processed_at");

                    b.Property<string>("ProcessedContent")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("processed_content");

                    b.Property<string>("RawInputId")
                        .IsRequired()
                        .HasColumnType("varchar(95)")
                        .HasColumnName("raw_input_id");

                    b.HasKey("Id");

                    b.HasIndex("RawInputId")
                        .IsUnique();

                    b.ToTable("ai_processing_results", (string)null);
                });

            modelBuilder.Entity("VocalClerk.Domain.Entities.Category", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("varchar(7)")
                        .HasColumnName("color");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("icon");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_default");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("name");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("varchar(95)")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("categories", (string)null);
                });

            modelBuilder.Entity("VocalClerk.Domain.Entities.Event", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("category");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasColumnType("longtext")
                        .HasColumnName("description");

                    b.Property<DateTime?>("EventTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("event_time");

                    b.Property<string>("Severity")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("severity");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("title");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("varchar(95)")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("events", (string)null);
                });

            modelBuilder.Entity("VocalClerk.Domain.Entities.EventTag", b =>
                {
                    b.Property<long>("EventId")
                        .HasColumnType("bigint")
                        .HasColumnName("event_id");

                    b.Property<long>("TagId")
                        .HasColumnType("bigint")
                        .HasColumnName("tag_id");

                    b.HasKey("EventId", "TagId");

                    b.HasIndex("TagId");

                    b.ToTable("event_tags", (string)null);
                });

            modelBuilder.Entity("VocalClerk.Domain.Entities.RawInput", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(95)")
                        .HasColumnName("id");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("content");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("InputType")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("input_type");

                    b.Property<bool>("Processed")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("processed");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("varchar(95)")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("raw_inputs", (string)null);
                });

            modelBuilder.Entity("VocalClerk.Domain.Entities.Tag", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("name");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("varchar(95)")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("tags", (string)null);
                });

            modelBuilder.Entity("VocalClerk.Domain.Entities.Task", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<long?>("CategoryId")
                        .HasColumnType("bigint")
                        .HasColumnName("category_id");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("completed_at");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasColumnType("longtext")
                        .HasColumnName("description");

                    b.Property<DateTime?>("DueDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("due_date");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_completed");

                    b.Property<string>("OriginalInput")
                        .HasColumnType("longtext")
                        .HasColumnName("original_input");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("priority");

                    b.Property<string>("RawInputId")
                        .HasColumnType("varchar(95)")
                        .HasColumnName("raw_input_id");

                    b.Property<DateTime?>("ReminderTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("reminder_time");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("title");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("varchar(95)")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("RawInputId");

                    b.HasIndex("UserId");

                    b.ToTable("tasks", (string)null);
                });

            modelBuilder.Entity("VocalClerk.Domain.Entities.TaskTag", b =>
                {
                    b.Property<long>("TaskId")
                        .HasColumnType("bigint")
                        .HasColumnName("task_id");

                    b.Property<long>("TagId")
                        .HasColumnType("bigint")
                        .HasColumnName("tag_id");

                    b.HasKey("TaskId", "TagId");

                    b.HasIndex("TagId");

                    b.ToTable("task_tags", (string)null);
                });

            modelBuilder.Entity("VocalClerk.Domain.Entities.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(95)")
                        .HasColumnName("id");

                    b.Property<bool>("AccountLocked")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("account_locked");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("email");

                    b.Property<int>("FailedLoginAttempts")
                        .HasColumnType("int")
                        .HasColumnName("failed_login_attempts");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("last_login_at");

                    b.Property<DateTime?>("LockedUntil")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("locked_until");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("password_hash");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("username");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("VocalClerk.Domain.Entities.UserSettings", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<string>("AiModel")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("ai_model");

                    b.Property<bool>("BiometricAuthEnabled")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("biometric_auth_enabled");

                    b.Property<bool>("DarkMode")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("dark_mode");

                    b.Property<bool>("DataBackupEnabled")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("data_backup_enabled");

                    b.Property<bool>("NotificationsEnabled")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("notifications_enabled");

                    b.Property<string>("PreferredLanguage")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("preferred_language");

                    b.Property<int>("ReminderLeadTime")
                        .HasColumnType("int")
                        .HasColumnName("reminder_lead_time");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("varchar(95)")
                        .HasColumnName("user_id");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("username");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("user_settings", (string)null);
                });

            modelBuilder.Entity("VocalClerk.Domain.Entities.AIProcessingResult", b =>
                {
                    b.HasOne("VocalClerk.Domain.Entities.RawInput", "RawInput")
                        .WithOne("ProcessingResult")
                        .HasForeignKey("VocalClerk.Domain.Entities.AIProcessingResult", "RawInputId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RawInput");
                });

            modelBuilder.Entity("VocalClerk.Domain.Entities.Category", b =>
                {
                    b.HasOne("VocalClerk.Domain.Entities.User", "User")
                        .WithMany("Categories")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("VocalClerk.Domain.Entities.Event", b =>
                {
                    b.HasOne("VocalClerk.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("VocalClerk.Domain.Entities.EventTag", b =>
                {
                    b.HasOne("VocalClerk.Domain.Entities.Event", "Event")
                        .WithMany("Tags")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VocalClerk.Domain.Entities.Tag", "Tag")
                        .WithMany()
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Event");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("VocalClerk.Domain.Entities.RawInput", b =>
                {
                    b.HasOne("VocalClerk.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("VocalClerk.Domain.Entities.Tag", b =>
                {
                    b.HasOne("VocalClerk.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("VocalClerk.Domain.Entities.Task", b =>
                {
                    b.HasOne("VocalClerk.Domain.Entities.Category", "Category")
                        .WithMany("Tasks")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("VocalClerk.Domain.Entities.RawInput", "RawInput")
                        .WithMany("Tasks")
                        .HasForeignKey("RawInputId");

                    b.HasOne("VocalClerk.Domain.Entities.User", "User")
                        .WithMany("Tasks")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("RawInput");

                    b.Navigation("User");
                });

            modelBuilder.Entity("VocalClerk.Domain.Entities.TaskTag", b =>
                {
                    b.HasOne("VocalClerk.Domain.Entities.Tag", "Tag")
                        .WithMany("TaskTags")
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VocalClerk.Domain.Entities.Task", "Task")
                        .WithMany("Tags")
                        .HasForeignKey("TaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tag");

                    b.Navigation("Task");
                });

            modelBuilder.Entity("VocalClerk.Domain.Entities.UserSettings", b =>
                {
                    b.HasOne("VocalClerk.Domain.Entities.User", "User")
                        .WithOne("Settings")
                        .HasForeignKey("VocalClerk.Domain.Entities.UserSettings", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("VocalClerk.Domain.Entities.Category", b =>
                {
                    b.Navigation("Tasks");
                });

            modelBuilder.Entity("VocalClerk.Domain.Entities.Event", b =>
                {
                    b.Navigation("Tags");
                });

            modelBuilder.Entity("VocalClerk.Domain.Entities.RawInput", b =>
                {
                    b.Navigation("ProcessingResult");

                    b.Navigation("Tasks");
                });

            modelBuilder.Entity("VocalClerk.Domain.Entities.Tag", b =>
                {
                    b.Navigation("TaskTags");
                });

            modelBuilder.Entity("VocalClerk.Domain.Entities.Task", b =>
                {
                    b.Navigation("Tags");
                });

            modelBuilder.Entity("VocalClerk.Domain.Entities.User", b =>
                {
                    b.Navigation("Categories");

                    b.Navigation("Settings");

                    b.Navigation("Tasks");
                });
#pragma warning restore 612, 618
        }
    }
}
